CREATE TABLE dev_online_itil_execute(                              
	id varchar(32) not null comment '主键',
	itil_number varchar(100) not null comment 'itil申请单编号 ',
	itil_sourceId varchar(100) comment '来源ID GEN000002',
	itil_assignee varchar(100) comment '处理人 文本 00203045',
	itil_category varchar(100) comment '类别 文本 流程管理',
	itil_subcategory varchar(100) comment '子类别 文本 ITIL系统',
	itil_businessArea varchar(100) comment '小类别 文本 其他',
	itil_status varchar(100) comment '状态 文本 待审批',
	itil_requestor varchar(100) comment '申请人 文本 036131',
	itil_title varchar(400) comment '标题 文本 评估体系平台系统请求',
	itil_description varchar(1000) comment '申请内容 ',
	itil_plannedEnd varchar(100) comment '期望完成时间 日期时间 2015-12-10T17:00:00+00:00',
	itil_requestedDate varchar(100) comment '申请时间 日期时间 2015-12-07T14:02:07+00:00',
	itil_source varchar(100) comment '来源 文本 cloud',
	itil_openedBy varchar(100) comment '创建人 文本 cmb.int.cloud',
	create_time datetime comment '创建时间',
	create_user varchar(32) comment '创建人员id',
	update_time datetime comment '修改时间',
	update_user varchar(32) comment '修改人员id',
	state tinyint default 1 comment '状态 0 代表已删除，1代表正常',
	primary key (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 ROW_FORMAT=DYNAMIC collate=utf8_bin COMMENT '设备上线批次itil工单执行情况表';
